### ISSUE TITLE
Shopping Basket shows wrong number of requests

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#156]
The shopping basket increments the number of items in the basket when an existing request has new fields added to it. This results in a mismatch between the real number of requests and the total being shown by the shopping trolly. In this example there are only 4 requests.
![image](https://user-images.githubusercontent.com/110250803/203595138-eb8d0b4c-c700-43bf-80e8-96ef82415553.png)

**Comment by pjmonks** [comment]
@NigelPalmer What are the steps you did to make this happen? I can't seem to replicate this myself.

**Comment by NigelPalmer** [comment]
@pjmonks , I can create this problem by going to "Browse".  Select a schema and a data class and then click "view details". Then tick one of the fields that isn't already in one of your requests. Scroll to the bottom of the page and click "With selected...".  Choose one of your existing requests. Then once it has been updated click on "View requests". The basket will now be showing the wrong number of items.
