### ISSUE TITLE
Request list: Display a little messy at smaller browser sizes

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#157]
The list of requests is truncating request names and the "submitted" label at smaller screen sizes. It would be good if this could be presented in a slightly neater way.
![image](https://user-images.githubusercontent.com/110250803/203595830-f1b53393-2979-4d30-b6d3-238034777430.png)

**Comment by pjmonks** [comment]
@NigelPalmer Does this issue become obsolete because of #168 ?

**Comment by NigelPalmer** [comment]
Yes, this task is now obsolete. Closing task.
