### ISSUE TITLE
Persist query in mauro database.

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#164]
The data behind the query builder UI can be simply piped into a json format. Json is the most sensible version of the data to save, since it gives us the most flexibility in transforming the data into the three different desired formats, UI representation, Simple Query Language, and SQL. Two queries will be required to be saved, Cohort and Data. Two new fields need to be added to the datamodel.data_model table to hold the json data for these queries. Then api requests will need to be identified and updated to allow the new fields to be inserted and updated as required. Api requests that return data from the datamodel.data_model table will also need updating to include the new fields.

**Comment by pjmonks** [comment]
Instead of adding new fields to the `DataModel` domain, the cohort and data queries will be created as rules on the request data model:

```
Data Model: "My Request"
  Rule: "Cohort Query"
    Representation: [JSON] "..."
  Rule: "Data Query"
    Representation: [JSON] "..."
```
