### ISSUE TITLE
search-as-you-type required for 'model references'

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#169]
Some data elements that use the 'model reference' type will point at a terminology - usually ICD10 or OPCS4. Terminologies may have a few thousand terms, so a standard checkbox won't work for those, but we can probably make a search-as-you-type select box work for most use cases, alongside the ability to add a search term (prefix / regex / whatever). An api call would be needed to get the list of options since we wouldn't want a page to load 1000s of items. A material design search-as-you-type control should be able to be added to the query builder.

**Comment by pjmonks** [comment]
@jamesrwelch As I mentioned in #166 , it would be useful if we could be provided a sample data model which represents this scenario of having a large number of terms.
