### ISSUE TITLE
Create Template models

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#203]
# Description

The Mdm Explorer needs to display a list of templates that a user can copy to create a new request from. Templates will simply be data models that are not editable and flagged as Templates.

# UX

Add a new item to the menu bar at the top called "Templates". When clicked this will take the user to a new page that will show a list of templates. 
![TemplatesMenu](https://user-images.githubusercontent.com/110250803/211838802-019cddad-f842-4672-b052-1ce995343dc8.jpg)

The template list should be the same as the requests list only without the "submitted" or "unsent" badge being visible. The copy button should also be available on this page.
![TemplatesList](https://user-images.githubusercontent.com/110250803/211836939-28296e6f-ad77-4bbb-876e-9687f1e35c01.jpg)

When the "View Details" link is clicked, the user will go to a page that looks like the request details page without the "submitted" or "unsent" badge being visible. The "Remove" button should also not be visible.
![TemplateDetail](https://user-images.githubusercontent.com/110250803/211837005-e1b6681e-336a-4b4d-a4c0-862db24d33dc.jpg)

# Additional context

It needs to be established how a data model is flagged as a template so that it will only appear in the Templates list for all users.

**Comment by pjmonks** [comment]
While thinking about how this will be implemented, I thought about the "Add to request" buttons dotted around the UI in various places:

![image](https://user-images.githubusercontent.com/3219480/212346052-ed3f12cb-792c-47aa-a193-d60254e0e8aa.png)

![image](https://user-images.githubusercontent.com/3219480/212346099-92b1f4f1-ea86-4c0d-8225-05b535e581fc.png)

This may also be a good point to select from a template _whilst_ creating the new request and adding the elements to it. However, this will increase the complexity of this task, so this may become a follow up task instead.
