### ISSUE TITLE
Make current data requests clickable

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#207]
# Description

When browsing websites if I see a large box with rounded corners I expect to be able to click on it and something to happen. This is not the case on the MDM Explorer home page. At the bottom of the page is a section labelled "Your current data requests" with such boxes displayed. The user should be able to click on these boxes and be taken to the relevant "Requests" page. Then the "Manage my requests" button can be removed since it will become redundant. If a user wishes to see all their requests they can use the shopping cart icon in the top right. 

# Additional context

In the following screen shot the "COVID" and "Date Test" boxes should be clickable.
![image](https://user-images.githubusercontent.com/110250803/211856462-7d1f0233-abb2-41b8-950b-854bf26fc237.png)

**Comment by NigelPalmer** [comment]
In addition to this, we have noticed that the request boxes are of different sizes depending on the length of the description. These should be standardised, possibly truncating descriptions with ellipses to indicate their is more to read.  All the boxes should be the same height, but we don't want to show a really tall box if it is not needed.

**Comment by CristianGimenez** [comment]
Cards are now clickable and the bottom button is removed.

As per the ellipsis:

Cards have now fixed height. And I managed the amount of lines to be shown using [line-clamp webkit](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) which has the following compatibility 
![image](https://user-images.githubusercontent.com/76041705/212874850-9e4be9fb-739f-46ac-a15f-04b77e7a1230.png)

It looks like this in the end:
![image](https://user-images.githubusercontent.com/76041705/212874971-d8d8ae75-540f-4d80-a466-2bc1297d6f9f.png)
