### ISSUE TITLE
Standardise Submitted/Unsent badge alignment

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#208]
# Description

When viewing a Request the Submitted/Unsent badge appears on the right of the list. But when the details are viewed the badge appears on the left. This is a poor user experience and the position of the badge should be consistent on all pages.

# Additional context
List of requests:
![image](https://user-images.githubusercontent.com/110250803/211857736-5fd5285c-f4e0-44b8-a1af-5571e68ca4fb.png)

View details:
![image](https://user-images.githubusercontent.com/110250803/211857885-c02eab90-1662-476f-be5f-e7a076c7d71b.png)

**Comment by OButlerOcc** [comment]
![image](https://user-images.githubusercontent.com/85611988/212674394-93bb947e-7c15-4b2e-b19a-7e5f776d453a.png)
![image](https://user-images.githubusercontent.com/85611988/212674443-367c050b-38e3-4c0c-9a16-529902a6955a.png)
![image](https://user-images.githubusercontent.com/85611988/212674500-de92efea-c48f-4187-b3f1-a0d733bd9686.png)
Updated look
