### ISSUE TITLE
Make the request query editor page consistent with the rest of the request management pages

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#209]
# Description

The request query editor page should be styled to look more like the other request management pages. I.e it should have a dark green bar and sandy coloured background. At the moment it is plain white. The positioning of the name of the request and the badge also needs to be considered. See #208  that has been raised about wider reaching badge alignment issues.

# Additional context

Cohort Query Editor, lacking branding:
![image](https://user-images.githubusercontent.com/110250803/211859071-222db4d7-fdb0-47ad-b231-f3a4708ca027.png)

Cohort Query presented on details page. The editor needs to be branded to adhere to this scheme:
![image](https://user-images.githubusercontent.com/110250803/211858920-4056003f-3f10-4845-a607-7c83c5439279.png)

**Comment by pjmonks** [comment]
I am making some changes in #203 for consistency which may help with this.
