### ISSUE TITLE
The Copy/Create menu does not ask for confirmation

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#239]
# Description

The Copy/Create menu does not ask for confirmation when the user ticks or unticks an item. This should, since the user may not fully understand the implications of clicking those boxes. Please update the menu so that the user is prompted for confirmation for the action.

# Additional context
![image](https://user-images.githubusercontent.com/110250803/216314131-203ba3c6-8d50-4590-a25a-529790eea581.png)

**Comment by NigelPalmer** [comment]
When using the browse options it is nice to be able to tick things without being prompted for confirmation. Where as in the requests page, I think the prompt would be useful. Maybe this feature is not required? I'm not sure having different behaviours in different places is a good idea. @pjmonks , I would appreciate your thoughts on this.

**Comment by pjmonks** [comment]
Having lots of popups appear may seem a bit too distracting for a user. My thinking is it could end up like the "cookie banner hell" of every webpage at the moment - no-one will really pay attention if they are bombarded by lots of confirmation messages, and just click the first button they see.

It might be best to get actual user feedback from real users on this one first - is it actually confusing for them? What do they find confusing about it?

One other option is to redesign the entire popup menu control to immediately launch a dialog of options, maybe like a wizard UI:

- Explain with text the options available
- Clearly define that the user can copy items to X request
- Or perform some other action
