### ISSUE TITLE
Add ordering options to Request lists

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#240]
# Description

gh-202 added ordering to sort lists of Requests by name in ascending order to make them easier to manage. This sorting could be improved to allow other sorting options. These options would be:

1. Sort by name ascending (already implemented)
2. Sort by name descending.
3. Sort by created date ascending.
4. Sort by created date descending

Ideally the sort option would be remembered so that the next time the user visits that screen they would see the list in the same situation as they last viewed it. This should be remembered even if the user logs out and in again.

# Additional context

A control will be required to allow the user to choose their sorting option.

**Comment by pjmonks** [comment]
We can only sort Data Requests by label/name at the moment. Looking into the Mauro endpoint used to fetch the list, `GET /folders/{folderId}/dataModels`, you can pass the usual sort/filter/page arguments to the API but they will be ignored when filtering by a parent folder ID. This is a backend issue that would need fixing.

In the meantime, I can organise the returned list in TypeScript code. However, the objects returned by the Mauro endpoint include just the `label`, no date fields such as `lastUpdated`, so I am limited in what is possible.
