### ISSUE TITLE
Add Theming to Mdm Explorer: Load colours and fonts from backend

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#274]
# Depends on

* #264
* MauroDataMapper-Plugins/mdm-plugin-explorer#18
* MauroDataMapper-Plugins/mdm-plugin-explorer#19

# Description

Load api properties to set the theme colours and fonts of the Mdm Explorer website.

# Additional context

Update the `ThemeService.loadTheme` method and replace the hard coded values with loaded api property values. Use the new `/explorer/theme` endpoint which will return a JSON response like this:

```json
{
    "count": 3,
    "items": [
        {
            "id": "f5a897f5-3e69-4c49-9795-827caacb27d9",
            "key": "material.colors.primary",
            "value": "#19381f"
        },
        {
            "id": "a83f3d68-c211-4c35-9bf9-83ffa91e328e",
            "key": "material.colors.accent",
            "value": "#cdb980"
        },
        {
            "id": "0eabbbe6-caee-4e4d-883c-84c70289849c",
            "key": "material.colors.warn",
            "value": "#a5122a"
        }
    ]
}
```

See MauroDataMapper-Plugins/mdm-plugin-explorer#18 for a table of properties that will returned, noting:

1. The `explorer.theme.` prefix will be removed from this list
2. The list returns a cutdown version of a list of API Property objects - only the key and value are really needed.
3. For typography values returned, they will look similar to "14px, 20px, 400". These are space separated values in this order: `fontSize`, `lineHeight`, `fontWeight`

Ensure these map to a `Theme` object correctly to work with the `ThemeService.applyTheme()` function.

**Comment by pjmonks** [comment]
Two comments:

1. This list of properties might need to be reviewed if PR #282 is accepted.
2. I think API property names cannot contain digits, so `explorer.theme.typography.body.1` would not work. Might need to confirm that for definite, but I seem to remember having issues with naming API properties like this.
