### ISSUE TITLE
Spinner for Removal of data elements in requests does not end

### ISSUE THREAD

**Issue by OButlerOcc** [MauroDataMapper/mdm-explorer#284]
To Replicate:
Create a request.
Add some data elements.
Remove a data element individually or via selection ticks and remove selected.

The Spinner appears with "removing x items" 
The spinner never closes.
Refresh the page. 
The items are removed sucessfully.

**Comment by OButlerOcc** [comment]
![image](https://user-images.githubusercontent.com/85611988/220334790-f07f9c0a-642e-4113-bc10-52efec118dd1.png)

**Comment by pjmonks** [comment]
I think this is a duplicate of #285 so I will close this issue.
