### ISSUE TITLE
Data Submission - Select Project step

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#394]
# Description

When the user clicks the "Finalise and Submit" button, the first thing they should be shown is a dialog box asking them to select a Project to associate the Data Request with. They should only be able to view projects that they are allowed to see. The user should be able to cancel the process at this point. This dialog must be shown before any other finalisation and submission processing is executed.

# Technical

### Project Dialog
There is already a "Create new request" dialog (`RequestTypeDialogComponent`) that could be utilised for this purpose. It looks like this:
![image](https://github.com/MauroDataMapper/mdm-explorer/assets/110250803/2981e23f-3e83-4ea8-8d0e-f5ae49585ce0)

In this instance we would want to hide the "Request Type" dropdown field and automatically select "Data" as the request type behind the scenes. Also we would want the title to be changed to "Create new Data request". The "Project" dropdown is already being filtered to the ones that are allowed to be seen. When the "Create" button is clicked, instead of a request being created, the next step in the submission process should be run.

### GetProjectStepService
Create a new service called `GetProjectStepService` that inherits from `SubmissionStepService`. This should implement the following:

1. executionRequired: Check to see if a Data request exists for the dataSpecificationId that is being submitted. (You will be able to call `/request-for-data-specification/{mauroDataSpecificationId}` to get this information, see maurodatamapper/sde-core#191 ) If there IS NOT a data request, then return true, otherwise, return false.
2. execute: Display the `RequestTypeDialogComponent` as described in the "Project Dialog" section above. When the confirm button is clicked the `stepResult.keyMap` must contain an entry that holds the Project Id that was selected. If the cancel button is clicked then we need to add something to the `stepResult.keyMap` to indicate that this has happened.
3. getResult: Get the requestId for the dataSpecificationId that is being submitted. Then load the matching request for that requestId and extract the projectId from it. Then, as in the step above, return a `stepResult.keyMap` that contains that projectId.

### FinaliseStepService
Update the `FinaliseStepService` so that it simply passes through the projectId. In other words, we need to extract the projectId from the passed in `keyMap`, and then include it in the  `stepResult.keyMap`. This will need to be done for both the execute and `getResult` functions.

### SubmissionService
Add the `GetProjectStepService` to the beginning of the `stepList`.
```stepList = [new GetProjectStepService(), new FinaliseStepService()]```

We need to handle the cancellation of the `RequestTypeDialogComponent`. This could be done by including a check in each subsequent executionRequired step, but this seems clumsy. The other way is that the `stepResult` class has an `abort` flag that defaults to false, and when cancel is clicked it is set to true. Then the recursive submitStep checks this `abort` flag to determine whether it will run subsequent steps.

**Comment by abwilson23** [comment]
Closing this as we are combining this step with the next step 'CreateDataRequest': #396
