### ISSUE TITLE
Planning to implement "Status Timeline" in Requests Popup 

### ISSUE THREAD

**Issue by OButlerOcc** [MauroDataMapper/mdm-explorer#436]
# Overview

**Current Implementation**
For each request, researches can read what status it is, without having any clue how many steps are needed before the request will be approved/fulfilled.

-> We want to improve the information currently provided, by adding a visual representation of how far a request progressed.
This representation will be available within the popup opened when a request is selected and opened. 

# Requirements
Following what have been described in the above section (and, in more details from epic #425):
- This representation should be available for all requests for that researcher
- This representation should display the current status and how many statuses there are
- This representation should show where on the cycle the current status is
- This representation should be available/visible within the request popup
- This representation will group statuses into a more readable format (e.g. In review to represent in review Assigned, in review feasibility etc.)

## List of all Status Request 
[currently available/implemented]

| Status | Description | Comment | 
| :--- | :--- | :--- |
| Draft (researcher) | Request submission approval, Close Request | Not in Timeline |
| Awaiting approval (approver) | Approve, Return to author |  In Research Timeline - Not in Admin Timeline |
| Awaiting pickup (administrator) | Assign, Return to author | In Both Timelines |
| In review, assigned (administrator) | Assign, Record admin approval, Request management approval, Return to author | In Both Timelines |
| In review, feasibility (administrator) | Assign, Record management approval, Request governance approval, Return to author | In Both Timelines |
| In review, project scope (administrator) | Assign, Record management approval, Request governance approval, Return to author | In Both Timelines |
| In review, governance (administrator) | Assign, Record governance approval, Return to author | In Both Timelines |
| Approved, pending (administrator) | Assign, Schedule, Return to author | In Both Timelines |
| Approved, in progress (administrator) | Assign, Complete, Return to author | In Both Timelines |
| Complete, awaiting acknowledgement (researcher) | Acknowledge, Reject | In Both Timelines |
| Returned (researcher) | Request submission approval, Close Request | In Both Timelines |
| Closed (researcher) | Reopen | In Both Timelines |

> [!IMPORTANT] 
Requests are not going through all statuses. Each request type has its own specific timeline
It worth to consider these status "grouped" and having 'simplified' version with 6 main statuses like:
`Awaiting -> In review -> Approved -> Returned -> Complete -> Closed `
A new TimeLineGroup property will be added in order to make possible grouping status and most of all make them independent from the status itself (status could change name, new status can be added within the same group or even new groups could be added -> that won't change how the timeline will be structured)

## Possible issues (need to be investigated)
- The representation will need to be informed by the backend of the status flow, as it may change
- The backend workflow json does not currently indicate stage flow, it will need to be processed

## Example design drawings:
Example designs drawings: Stepper and/or Timeline
Here some useful examples: 
- https://www.primefaces.org/primeng-v16-lts/timeline
- https://v5.material.angular.io/components/stepper/overview
- https://primeng.org/stepper

### For the full list of tasks see:
- MauroDataMapper/mdm-explorer#425

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by giovannaOCC** [comment]
Fully defined - Relative issues to complete the requirements have been opened
