### ISSUE TITLE
Understand and create designs for (Ms 4)

### ISSUE THREAD

**Issue by OButlerOcc** [MauroDataMapper/mdm-explorer#437]
Get onboarded onto project via meeting with Nigel
Finish up some Pull requests for NHSDD
Meet with Giovanna to discuss the milestone 
Meet with Nigel to clarify Understanding of the expected outputs

Understand the goal of creating the visual representation for Mdm-researcher-ui to view their requests

- Create a list of user requirements
- Create a list of expected tasks
- Create some visual designs
- List expected issues
- Seek clarification where unsure

Understand the goal of creating the visual representation for Mdm admins to view all requests

- Create a list of user requirements
- Create a list of expected tasks
- Create some visual designs
- List expected issues
- Seek clarification of understanding
- Clarify if board interaction is a requirement.

Outputs:

Document of notes and questions and clarifications, use the formatted stuff below but here as a record
https://systemccom-my.sharepoint.com/:w:/g/personal/oliver_butler_systemc_com/EVD8RZ0jvZVNlPY5_4L3decBDkLROivvxlbwnaPAMUBryQ?e=nVnMH2

Design sheet for the Researcher UI Visualisation and Admin UI Visualisation Board
MauroDataMapper/sde-admin-ui#191

**Comment by giovannaOCC** [comment]
This issue can be closed as it has been fully discussed a new planning issues fully defined in :
MauroDataMapper/sde-admin-ui#191
