### ISSUE TITLE
Show TimeLine component in request popup [for researchers]

### ISSUE THREAD

**Issue by giovannaOCC** [MauroDataMapper/mdm-explorer#448]
## Pre-Requisite

This issue can be started after :
- [x] MauroDataMapper/sde-resources#130

## Description
When a researcher click on any of their requests a popup is showed containing all the information related to that request.
Immediately after the Title, within the popup, we want to add the TimeLine component that will show both the current status and how far the request has progressed.

**Comment by OButlerOcc** [comment]
closed as this is in the dialog and does not need a separate task
