### ISSUE TITLE
Data Specifications: only 10 columns per table are displayed when viewing

### ISSUE THREAD

**Issue by joe-crawford** [MauroDataMapper/mdm-explorer#454]
# Description

When viewing a data specification at a URL like `http://localhost:4201/#/dataSpecifications/{{uuid}}`, only 10 data elements per selected data class are displayed when viewing, even if more were selected.
# Steps to reproduce

Using a root data model which contains a table data class with more than 10 column data elements, build a query selecting all the elements on that data class. When viewing the data specification, only 10 data elements show under that data class.
# Expected behavior

There should be a way to view more/all of the data elements selected.
# Screenshots

`inpatient_encounter` had more than the displayed 10 data elements selected:

<img width="1343" alt="Screenshot 2024-09-24 at 4 31 05 PM" src="https://github.com/user-attachments/assets/acd9f0a0-47ba-4dd5-8cd4-b6ff9f21de3c">

# Environment

latest develop of `mdm-explorer` and `mdm-plugin-explorer`

**Comment by NigelPalmer** [comment]
The first thing to check is whether the missing fields are present when viewing the Data Specification in the MDM. It is possible that they were not copied in the first place.

**Comment by joe-crawford** [comment]
@NigelPalmer, yes I can see all the elements that were copied (whole table in each case, more than 10) in mdm-ui. I can also see the full list in the dropdowns in the query builder in mdm-explorer. I am guessing the mdm-explorer dataSpecifications page is just hitting a default limit of 10 on the /dataElements request which can be overridden with `?max=9999` or similar.

**Comment by NigelPalmer** [comment]
Thanks for checking Joe. Just a display problem then to resolve.

**Comment by joe-crawford** [comment]
Have tweaked this on `feature/demo` branch by hard coding a max value in data-model.service.ts `getDataElementsForDataClass`

**Comment by NigelPalmer** [comment]
We need to look at Joe's solution and integrate it into develop.
